# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'maquettepObRpg.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from core import *


class Ui_MainWindow(QMainWindow):

    def __init__(self):
        super().__init__()
        self.core = Core(self)
        self.setupUi(self)
        self.core.updateChart()

    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.mainwindow = QWidget(MainWindow)
        self.mainwindow.setObjectName(u"mainwindow")
        self.leftTable = QTabWidget(self.mainwindow)
        self.leftTable.setObjectName(u"leftTable")
        self.leftTable.setGeometry(QRect(0, 10, 231, 591))
        self.infoCharte = QWidget()
        self.infoCharte.setObjectName(u"infoCharte")
        self.nameInput = QLineEdit(self.infoCharte)
        self.nameInput.setObjectName(u"nameInput")
        self.nameInput.setGeometry(QRect(30, 70, 171, 20))
        self.descriptionInput = QLineEdit(self.infoCharte)
        self.descriptionInput.setObjectName(u"descriptionInput")
        self.descriptionInput.setGeometry(QRect(30, 130, 171, 20))
        self.nameLabel = QLabel(self.infoCharte)
        self.nameLabel.setObjectName(u"nameLabel")
        self.nameLabel.setGeometry(QRect(30, 50, 91, 21))
        self.descriptionState = QLabel(self.infoCharte)
        self.descriptionState.setObjectName(u"descriptionState")
        self.descriptionState.setGeometry(QRect(30, 100, 81, 31))
        self.preambleInput = QTextEdit(self.infoCharte)
        self.preambleInput.setObjectName(u"preambleInput")
        self.preambleInput.setGeometry(QRect(30, 190, 171, 71))
        self.preambleState = QLabel(self.infoCharte)
        self.preambleState.setObjectName(u"preambleState")
        self.preambleState.setGeometry(QRect(30, 160, 71, 21))
        self.Title = QLabel(self.infoCharte)
        self.Title.setObjectName(u"Title")
        self.Title.setGeometry(QRect(10, 10, 131, 21))
        self.RootName = QLabel(self.infoCharte)
        self.RootName.setObjectName(u"RootName")
        self.RootName.setGeometry(QRect(20, 340, 101, 31))
        self.RootNameLabel = QLabel(self.infoCharte)
        self.RootNameLabel.setObjectName(u"RootNameLabel")
        self.RootNameLabel.setGeometry(QRect(20, 390, 71, 21))
        self.RootNameInput = QLineEdit(self.infoCharte)
        self.RootNameInput.setObjectName(u"RootNameInput")
        self.RootNameInput.setGeometry(QRect(20, 420, 181, 20))
        self.InitalStateLabel = QLabel(self.infoCharte)
        self.InitalStateLabel.setObjectName(u"InitalStateLabel")
        self.InitalStateLabel.setGeometry(QRect(20, 450, 91, 21))
        self.InitialState = QComboBox(self.infoCharte)
        self.InitialState.setObjectName(u"InitialState")
        self.InitialState.setGeometry(QRect(20, 490, 181, 22))
        self.line_2 = QFrame(self.infoCharte)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 300, 221, 21))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.UpdateChartButton = QPushButton(self.infoCharte)
        self.UpdateChartButton.setObjectName(u"UpdateChartButton")
        self.UpdateChartButton.setGeometry(QRect(70, 280, 75, 23))
        self.UpdateRootButton = QPushButton(self.infoCharte)
        self.UpdateRootButton.setObjectName(u"UpdateRootButton")
        self.UpdateRootButton.setGeometry(QRect(70, 530, 75, 23))
        self.leftTable.addTab(self.infoCharte, "")
        self.addState = QWidget()
        self.addState.setObjectName(u"addState")
        self.Title_2 = QLabel(self.addState)
        self.Title_2.setObjectName(u"Title_2")
        self.Title_2.setGeometry(QRect(10, 20, 111, 31))
        self.NameStateInput = QLineEdit(self.addState)
        self.NameStateInput.setObjectName(u"NameStateInput")
        self.NameStateInput.setGeometry(QRect(10, 80, 113, 20))
        self.nameLabel_2 = QLabel(self.addState)
        self.nameLabel_2.setObjectName(u"nameLabel_2")
        self.nameLabel_2.setGeometry(QRect(10, 60, 47, 13))
        self.EntryInput = QTextEdit(self.addState)
        self.EntryInput.setObjectName(u"EntryInput")
        self.EntryInput.setGeometry(QRect(10, 150, 201, 71))
        self.EntryLabel = QLabel(self.addState)
        self.EntryLabel.setObjectName(u"EntryLabel")
        self.EntryLabel.setGeometry(QRect(10, 130, 47, 13))
        self.TransitionLabel = QLabel(self.addState)
        self.TransitionLabel.setObjectName(u"TransitionLabel")
        self.TransitionLabel.setGeometry(QRect(20, 230, 71, 31))
        self.transitionList = QScrollArea(self.addState)
        self.transitionList.setObjectName(u"transitionList")
        self.transitionList.setGeometry(QRect(10, 260, 181, 80))
        self.transitionList.setWidgetResizable(True)
        self.transitionList.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 179, 78))
        self.TransitionListContent = QListWidget(self.scrollAreaWidgetContents)
        self.TransitionListContent.setObjectName(u"TransitionListContent")
        self.TransitionListContent.setGeometry(QRect(0, 0, 181, 192))
        self.transitionList.setWidget(self.scrollAreaWidgetContents)
        self.AddStateButton = QPushButton(self.addState)
        self.AddStateButton.setObjectName(u"AddStateButton")
        self.AddStateButton.setGeometry(QRect(60, 360, 75, 23))
        self.AddTransitionLabel = QLabel(self.addState)
        self.AddTransitionLabel.setObjectName(u"AddTransitionLabel")
        self.AddTransitionLabel.setGeometry(QRect(10, 420, 121, 21))
        self.targetInput = QComboBox(self.addState)
        self.targetInput.setObjectName(u"targetInput")
        self.targetInput.setGeometry(QRect(70, 460, 141, 22))
        self.targetLabel = QLabel(self.addState)
        self.targetLabel.setObjectName(u"targetLabel")
        self.targetLabel.setGeometry(QRect(10, 460, 47, 13))
        self.eventInput = QComboBox(self.addState)
        self.eventInput.setObjectName(u"eventInput")
        self.eventInput.setGeometry(QRect(70, 500, 141, 22))
        self.EventLabel = QLabel(self.addState)
        self.EventLabel.setObjectName(u"EventLabel")
        self.EventLabel.setGeometry(QRect(10, 500, 47, 13))
        self.AddStateButton_2 = QPushButton(self.addState)
        self.AddStateButton_2.setObjectName(u"AddStateButton_2")
        self.AddStateButton_2.setGeometry(QRect(30, 540, 141, 23))
        self.line = QFrame(self.addState)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 390, 231, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.leftTable.addTab(self.addState, "")
        self.EditState = QWidget()
        self.EditState.setObjectName(u"EditState")
        self.SelectStateEditInput = QComboBox(self.EditState)
        self.SelectStateEditInput.setObjectName(u"SelectStateEditInput")
        self.SelectStateEditInput.setGeometry(QRect(10, 40, 191, 22))
        self.SelectStateLabel = QLabel(self.EditState)
        self.SelectStateLabel.setObjectName(u"SelectStateLabel")
        self.SelectStateLabel.setGeometry(QRect(20, 13, 71, 20))
        self.line_3 = QFrame(self.EditState)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(0, 100, 231, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.NameLabel = QLabel(self.EditState)
        self.NameLabel.setObjectName(u"NameLabel")
        self.NameLabel.setGeometry(QRect(10, 120, 61, 21))
        self.NameStateInput_2 = QLineEdit(self.EditState)
        self.NameStateInput_2.setObjectName(u"NameStateInput_2")
        self.NameStateInput_2.setGeometry(QRect(10, 150, 181, 20))
        self.EntryLabel_2 = QLabel(self.EditState)
        self.EntryLabel_2.setObjectName(u"EntryLabel_2")
        self.EntryLabel_2.setGeometry(QRect(10, 200, 47, 13))
        self.EntryInput_2 = QTextEdit(self.EditState)
        self.EntryInput_2.setObjectName(u"EntryInput_2")
        self.EntryInput_2.setGeometry(QRect(10, 220, 201, 71))
        self.TransitionLabel_2 = QLabel(self.EditState)
        self.TransitionLabel_2.setObjectName(u"TransitionLabel_2")
        self.TransitionLabel_2.setGeometry(QRect(20, 310, 71, 31))
        self.transitionSelect = QComboBox(self.EditState)
        self.transitionSelect.setObjectName(u"transitionSelect")
        self.transitionSelect.setGeometry(QRect(20, 350, 191, 22))
        self.EditState_2 = QPushButton(self.EditState)
        self.EditState_2.setObjectName(u"EditState_2")
        self.EditState_2.setGeometry(QRect(20, 70, 75, 23))
        self.line_4 = QFrame(self.EditState)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(-10, 410, 231, 16))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.EditTrans = QPushButton(self.EditState)
        self.EditTrans.setObjectName(u"EditTrans")
        self.EditTrans.setGeometry(QRect(90, 380, 81, 23))
        self.saveState = QPushButton(self.EditState)
        self.saveState.setObjectName(u"saveState")
        self.saveState.setGeometry(QRect(170, 380, 51, 23))
        self.deleteState = QPushButton(self.EditState)
        self.deleteState.setObjectName(u"deleteState")
        self.deleteState.setGeometry(QRect(110, 70, 75, 23))
        self.targetLabel_2 = QLabel(self.EditState)
        self.targetLabel_2.setObjectName(u"targetLabel_2")
        self.targetLabel_2.setGeometry(QRect(20, 450, 47, 13))
        self.targetInput_2 = QComboBox(self.EditState)
        self.targetInput_2.setObjectName(u"targetInput_2")
        self.targetInput_2.setGeometry(QRect(70, 450, 141, 22))
        self.EventLabel_2 = QLabel(self.EditState)
        self.EventLabel_2.setObjectName(u"EventLabel_2")
        self.EventLabel_2.setGeometry(QRect(20, 500, 47, 13))
        self.eventInput_2 = QComboBox(self.EditState)
        self.eventInput_2.setObjectName(u"eventInput_2")
        self.eventInput_2.setGeometry(QRect(70, 500, 141, 22))
        self.AddTransitionLabel_2 = QLabel(self.EditState)
        self.AddTransitionLabel_2.setObjectName(u"AddTransitionLabel_2")
        self.AddTransitionLabel_2.setGeometry(QRect(70, 420, 121, 21))
        self.AddTransitionLabel_3 = QLabel(self.EditState)
        self.AddTransitionLabel_3.setObjectName(u"AddTransitionLabel_3")
        self.AddTransitionLabel_3.setGeometry(QRect(80, 110, 121, 21))
        self.AddNewTrans = QPushButton(self.EditState)
        self.AddNewTrans.setObjectName(u"AddNewTrans")
        self.AddNewTrans.setGeometry(QRect(0, 380, 81, 23))
        self.saveTrans = QPushButton(self.EditState)
        self.saveTrans.setObjectName(u"saveTrans")
        self.saveTrans.setGeometry(QRect(70, 530, 75, 23))
        self.leftTable.addTab(self.EditState, "")
        self.mainTable = QTabWidget(self.mainwindow)
        self.mainTable.setObjectName(u"mainTable")
        self.mainTable.setGeometry(QRect(240, 30, 521, 541))
        self.previewTable = QWidget()
        self.previewTable.setObjectName(u"previewTable")
        # PREVIEW WIDGET
        self.widget = QWidget(self.previewTable)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(20, 20, 481, 461))
        self.imgReceiver = QLabel(self.widget)
        self.refreshButton = QPushButton(self.previewTable)
        self.refreshButton.setObjectName(u"refreshButton")
        self.refreshButton.setGeometry(QRect(10, 490, 75, 23))
        self.mainTable.addTab(self.previewTable, "")
        self.codeTable = QWidget()
        self.codeTable.setObjectName(u"codeTable")
        self.codeContent = QTextEdit(self.codeTable)
        self.codeContent.setObjectName(u"codeContent")
        self.codeContent.setGeometry(QRect(0, 0, 521, 531))
        self.codeContent.setStyleSheet(u"background:rgb(32, 34, 35);\n"
"color:rgb(205, 205, 205)")
        self.exprotButton = QPushButton(self.codeTable)
        self.exprotButton.setObjectName(u"exprotButton")
        self.exprotButton.setGeometry(QRect(10, 490, 75, 23))
        self.mainTable.addTab(self.codeTable, "")
        MainWindow.setCentralWidget(self.mainwindow)
        # adding signal and slot 
        self.UpdateChartButton.clicked.connect(self.core.updateChart)
        self.UpdateRootButton.clicked.connect(self.core.updateChart)
        self.AddStateButton.clicked.connect(self.core.addState)
        self.AddStateButton_2.clicked.connect(self.core.addTransition)
        self.deleteState.clicked.connect(self.core.deleteState)
        self.EditState_2.clicked.connect(self.core.editState)
        self.saveState.clicked.connect(self.core.saveeditState)
        self.exprotButton.clicked.connect(self.core.exportYAML)
        self.refreshButton.clicked.connect(self.core.refreshPreview)
        self.AddNewTrans.clicked.connect(self.core.addNewTrans)
        self.retranslateUi(MainWindow)

        self.leftTable.setCurrentIndex(0)
        self.mainTable.setCurrentIndex(0)
        self.eventInput.addItems(['press','release','short','long'])

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.exprotButton.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.refreshButton.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.AddNewTrans.setText(QCoreApplication.translate("MainWindow", u"Add Transition", None))
        self.nameLabel.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.descriptionState.setText(QCoreApplication.translate("MainWindow", u"Description", None))
        self.preambleState.setText(QCoreApplication.translate("MainWindow", u"Preamble", None))
        self.Title.setText(QCoreApplication.translate("MainWindow", u"StateChart setting", None))
        self.RootName.setText(QCoreApplication.translate("MainWindow", u"State root setting", None))
        self.RootNameLabel.setText(QCoreApplication.translate("MainWindow", u"Root name", None))
        self.InitalStateLabel.setText(QCoreApplication.translate("MainWindow", u"Initial State", None))
        self.UpdateChartButton.setText(QCoreApplication.translate("MainWindow", u"Update", None))
        self.UpdateRootButton.setText(QCoreApplication.translate("MainWindow", u"Update", None))
        self.leftTable.setTabText(self.leftTable.indexOf(self.infoCharte), QCoreApplication.translate("MainWindow", u"Information", None))
        self.Title_2.setText(QCoreApplication.translate("MainWindow", u"Add State", None))
        self.nameLabel_2.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.EntryLabel.setText(QCoreApplication.translate("MainWindow", u"Entrry", None))
        self.TransitionLabel.setText(QCoreApplication.translate("MainWindow", u"Transition", None))
        self.AddStateButton.setText(QCoreApplication.translate("MainWindow", u"Add State", None))
        self.AddTransitionLabel.setText(QCoreApplication.translate("MainWindow", u"Add Transition", None))
        self.targetLabel.setText(QCoreApplication.translate("MainWindow", u"target", None))
        self.EventLabel.setText(QCoreApplication.translate("MainWindow", u"Event", None))
        self.AddStateButton_2.setText(QCoreApplication.translate("MainWindow", u"Add Transition to State", None))
        self.leftTable.setTabText(self.leftTable.indexOf(self.addState), QCoreApplication.translate("MainWindow", u"Add State", None))
        self.SelectStateLabel.setText(QCoreApplication.translate("MainWindow", u"Select State", None))
        self.NameLabel.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.EntryLabel_2.setText(QCoreApplication.translate("MainWindow", u"Entrry", None))
        self.TransitionLabel_2.setText(QCoreApplication.translate("MainWindow", u"Transition", None))
        self.EditState_2.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.EditTrans.setText(QCoreApplication.translate("MainWindow", u"Edit transition", None))
        self.saveState.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.deleteState.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.targetLabel_2.setText(QCoreApplication.translate("MainWindow", u"target", None))
        self.EventLabel_2.setText(QCoreApplication.translate("MainWindow", u"Event", None))
        self.AddTransitionLabel_2.setText(QCoreApplication.translate("MainWindow", u"Edite Transition", None))
        self.AddTransitionLabel_3.setText(QCoreApplication.translate("MainWindow", u"Edite State", None))
        self.saveTrans.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.leftTable.setTabText(self.leftTable.indexOf(self.EditState), QCoreApplication.translate("MainWindow", u"Edit State", None))
        self.mainTable.setTabText(self.mainTable.indexOf(self.previewTable), QCoreApplication.translate("MainWindow", u"Preview", None))
        self.mainTable.setTabText(self.mainTable.indexOf(self.codeTable), QCoreApplication.translate("MainWindow", u"Code", None))
    # retranslateUi





